Repository AY2021S2-CS2103T-T12-3/tp, pull requests merged in 2021-04, with the labels that each got.

#138 Add tag add and delete command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TagsUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTags.java
Labels: priority.High, type.Enhancement

#139 Bump sementic versioning to v1.3.0
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Task

#140 Update Ui.png
  docs/images/Ui.png
Labels: documentation

#209 Fix typo for tag and alias command result
  src/main/java/seedu/address/logic/commands/DeleteAliasCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
Labels: documentation, priority.Low

#217 Add yaowei-soc PPP
  docs/AboutUs.md
  docs/team/yaowei-soc.md
Labels: documentation, priority.High

#218 Add YP-PPP draft
  docs/AboutUs.md
  docs/team/oeiyiping.md
Labels: documentation, priority.High

#221 docs: Add PPP draft
  docs/AboutUs.md
  docs/team/tanboonji.md
Labels: documentation

#220 Add PPP for KI
  docs/AboutUs.md
  docs/team/darkdestry-t.md
Labels: documentation, priority.High

#219 docs: Add personal portfolio page draft
  docs/AboutUs.md
  docs/team/justgnohug.md
Labels: documentation, priority.High

#212 UG fixes based on PE suggestions
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListAliasCommand.java
  src/main/java/seedu/address/logic/commands/SelectClearCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SelectIndexCommand.java
  src/main/java/seedu/address/logic/commands/SelectShowCommand.java
Labels: documentation

#225 Fix duplicate person with same name in different capitalization
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug

#229 Fix existing command to be not alias-able
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/test/java/seedu/address/logic/parser/AddAliasCommandParserTest.java
Labels: type.Bug

#231 Add text wrap to all Person fields to fix truncation
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#236 docs: fix UG based on PED issues
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation

#238 Add email and filter commands to switch case in valid alias check
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High

#207 Remove sorted observableList from usage
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SelectIndexCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FieldsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/FieldsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/RemarkContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: priority.High

#226 Fix unexpected toggling for command panel and alias window
  src/main/java/seedu/address/ui/AutocompleteListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Bug

#233 Change addressbook.json to a-bashbook.json
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableAliasMap.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Medium

#240 docs: Update UG and DG for find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#244 Fix tags from allowing duplicates with different cases
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.Medium

#243 Fix command output for empty person list
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/commands/SelectIndexCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectIndexCommandTest.java
Labels: documentation

#239 Update FilterCommand messages
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation, priority.Medium

#257 General UG improvements
  docs/UserGuide.md
Labels: documentation

#252 fix: enforce trailing whitespace for prefixes
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#262 Improve code quality for autocomplete feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#254 Increment version and change output filename
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#267 Add class diagram for find command and its predicates
  docs/DeveloperGuide.md
  docs/diagrams/FindPredicateClassDiagram.puml
  docs/images/FindPredicateClassDiagram.png
Labels: documentation

#269 Update DG for Remarks
  docs/DeveloperGuide.md
  docs/diagrams/EditRemarkActivityDiagram.puml
  docs/images/EditRemarkActivityDiagram.png
Labels: documentation

#256 Update DG manual testing section
  docs/DeveloperGuide.md
Labels: documentation

#266 DG Updates for Autocomplete Feature
  docs/DeveloperGuide.md
  docs/diagrams/AutocompleteCommandsDiagram.puml
  docs/diagrams/AutocompleteFlagsDiagram.puml
  docs/diagrams/AutocompleteIndexDiagram.puml
  docs/images/AutocompleteCommandsDiagram.png
  docs/images/AutocompleteFlagsDiagram.png
  docs/images/AutocompleteIndexDiagram.png
Labels: documentation

#272 Add Effort section to appendix
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#258 UG Updates for Autocomplete and Command Flag meaning
  docs/UserGuide.md
Labels: documentation

#277 docs: Standardize terms that were used interchangeably
  docs/UserGuide.md
Labels: documentation
