Repository AY2021S2-CS2103T-T12-3/tp, pull requests merged in 2021-03, with the labels that each got.

#43 docs: update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#42 docs: update user guide
  docs/UserGuide.md
Labels: documentation

#44 docs: add aboutus image
  docs/images/justgnohUG.png
Labels: documentation

#45 docs: add aboutus image
  docs/images/oeiyiping.png
Labels: documentation

#47 docs: add profile image
  docs/images/chongyaowei.png
Labels: documentation, type.Task

#46 docs: add aboutus image
  docs/images/tanboonji.png
Labels: documentation

#48 docs: add ui image
  docs/images/Ui.png
Labels: documentation

#50 docs: fix incorrect filename
  docs/images/justgnohug.png
Labels: documentation

#49 docs: rename yaowei profile photo
  docs/images/yaowei-soc.png
Labels: documentation, type.Task

#53 docs: add about us image
  docs/images/darkdestry-t.png
Labels: documentation

#59 docs: update ci and codecov badge
  docs/index.md
Labels: documentation, priority.Low, severity.VeryLow

#69 Add component ownership to AboutUs
  docs/AboutUs.md
Labels: documentation

#71 Change flags to comply with Bash format (eg. from n/ to -n)
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: priority.Medium, type.Enhancement

#70 Add `filter` command to filter person list items
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/DisplayFilterPredicate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
Labels: priority.Medium, type.Enhancement

#75 fix: Add spacing between prefix and value in help messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Medium, type.Bug

#79 Fix Javadocs related to displayfilter predicate
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/model/Model.java
Labels: documentation, priority.Low

#77 Add Remarks feature to Person
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/DisplayFilterPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#76 Replace existing search with fuzzy search
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Story

#98 Add sample remarks to default contacts
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement

#106 Enable run assertions in build.gradle
  build.gradle
Labels: priority.High

#105 Improve UGDG for Remarks and Bash-like commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#113 Change help window user guide link
  build.gradle
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: severity.Low

#112 Add assert statement to FilterCommandParser
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: priority.High

#116 Update DG for Alias
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#117 Add assert when checking alias in AddCommandParser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: priority.High

#118 Add documentation for fuzzy find feature in developer guide
  docs/DeveloperGuide.md
Labels: severity.Low, type.Task

#120 Update UML diagram for Model to include Remark in Person class
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#121 Change alias UI from pop up dialog to use autocomplete panel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListAliasCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUniqueAliasMap.java
  src/main/java/seedu/address/model/UniqueAliasMap.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAliasCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UniqueAliasMapTest.java
  src/test/java/seedu/address/testutil/TypicalAliases.java
Labels: type.Enhancement

#119 Implement select command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_includes/image.html
  docs/diagrams/SelectCommandClassDiagram.puml
  docs/diagrams/SelectCommandParserSequenceDiagram.puml
  docs/images/SelectCommandClassDiagram.png
  docs/images/SelectCommandParserSequenceDiagram.png
  docs/images/SelectCommandParserSequenceDiagram_ref.png
  docs/images/UG_Select Indicator.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SelectClearCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SelectIndexCommand.java
  src/main/java/seedu/address/logic/commands/SelectShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectIndexCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/Extensions.css
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectClearCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectShowCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectIndexCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High
